on: push

name: test

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      CARGO_INCREMENTAL: 1
    steps:
      - uses: actions/checkout@v2
      - name: cache .cargo
        uses: actions/cache@v2
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
      - name: install toolchain
        uses: actions-rs/toolchain@v1
        with:
          components: rustfmt
      - name: cargo fmt
        uses: actions-rs/cargo@v1
        with:
          command: fmt
          args: -q --check
      - name: cargo test
        uses: actions-rs/cargo@v1
        with:
          command: test
          args: --all
